export const SET_ALL_ACTIVITIES = 'SET_ALL_ACTIVITIES';
export const SET_ACTIVITY_DETAIL = 'SET_ACTIVITY_DETAIL';
export const FETCH_CALLS_REQUEST = 'FETCH_CALLS_REQUEST';
export const FETCH_CALLS_SUCCESS = 'FETCH_CALLS_SUCCESS';
export const FETCH_CALLS_FAILURE = 'FETCH_CALLS_FAILURE';
export const UPDATE_CALL_SUCCESS = 'UPDATE_CALL_SUCCESS';
export const RESET_CALLS = 'RESET_CALLS';
